vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        artisans:
            uri_prefix: /images/artisans
            upload_destination: '%kernel.project_dir%/public/images/artisans'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
